"""Shared inventory input and pagination limits."""

INVENTORY_CODE_LIMIT = 64
INVENTORY_NAME_LIMIT = 200
INVENTORY_REFERENCE_LIMIT = 200
INVENTORY_NOTE_LIMIT = 1_000
BASE_UOM_LIMIT = 16
INVENTORY_PAGE_SIZE = 25
INVENTORY_PAGE_MAX = 100
